//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsAppApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupKullanici
    {
        public int GrupKullaniciID { get; set; }
        public int GrupID { get; set; }
        public int KullaniciID { get; set; }
        public Nullable<System.DateTime> KatilmaZamani { get; set; }
    
        public virtual Grup Grup { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
